### ISSUE TITLE
Molotov ebuild

### ISSUE THREAD

**Issue by Zatoichiben** [aaaaadrien/adrien-overlay#1]
Bonjour Adrien,

j'ai essayé de mettre Molotov je pense que l'adresse n'est plus bonne il manque la version 1.8.0
a la fin de:
https://desktop-auto-upgrade.s3.amazonaws.com/linux
mettre cela
https://desktop-auto-upgrade.s3.amazonaws.com/linux/1.8.0/
si c'est bien cà le problème.

**Comment by aaaaadrien** [comment]
Le script indique 
https://desktop-auto-upgrade.s3.amazonaws.com/linux/${PV}/molotov
PV prend la valeur de l'ebuild soit ici 1.8.0
Donc
https://desktop-auto-upgrade.s3.amazonaws.com/linux/1.8.0/molotov
Quelle est l'erreur ?
Tu peux poster le fichier build.log ? (chemin affiché dans la console normalement)

**Comment by Zatoichiben** [comment]
ok

**Comment by Zatoichiben** [comment]
Voila ce que j'ai pus récupérer .
ca tourne en boucle sans s'installer en faite.

**Comment by Zatoichiben** [comment]
Le build log est coupé entre 73 pour cent et 99 pour cent 
Ca vient de moi je t’ai évité le log entier vus que ca skip le téléchagement

Provenance : Courrier pour Windows 10

De : Adrien_D
Envoyé le :dimanche 12 novembre 2017 09:20
À : aaaaadrien/adrien-overlay
Cc : Zatoichiben; Author
Objet :Re: [aaaaadrien/adrien-overlay] Molotov ebuild (#1)

Le script indique
https://desktop-auto-upgrade.s3.amazonaws.com/linux/${PV}/molotov
PV prend la valeur de l'ebuild soit ici 1.8.0
Donc
https://desktop-auto-upgrade.s3.amazonaws.com/linux/1.8.0/molotov
Quelle est l'erreur ?
Tu peux poster le fichier build.log ? (chemin affiché dans la console normalement)
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by aaaaadrien** [comment]
je n'ai pas le log.
Poste le sur pastebin.com et mets l'URL ici :)

**Comment by Zatoichiben** [comment]
https://pastebin.com/SJ810FEt

**Comment by aaaaadrien** [comment]
OK
J'ai reproduit le pb, je regarde

**Comment by aaaaadrien** [comment]
Corrigé
Resynchronise en root avec layman -s adrien-overlay avant de réinstaller

**Comment by Zatoichiben** [comment]
OK merci Adrien,

moi qui pensait que c'était juste une histoire d'adresse de serveur.
je me fourvoyais complètement désolé de t'infliger ça un dimanche.

Je teste ton Overlay et si je tombe sur des problèmes je les ferais remonté
avec modération:)


2017-11-12 10:21 GMT+01:00 Adrien_D <notifications@github.com>:

**Comment by aaaaadrien** [comment]
Oui remontes, c'est comme ça que le tout progresse :)

**Comment by Zatoichiben** [comment]
Bon impeccable Molotov c'est installé
ça mis du temps mais je pense que c'est ma connexion
tout roule.
Merci bonne journée;)

2017-11-12 10:30 GMT+01:00 Adrien_D <notifications@github.com>:
